name: Docker Publish

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '0 5 * * 0'
  workflow_dispatch:

env:
  tag: latest
  project: factorio-status

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            dockerfile: Dockerfile
            platform: amd64
          -
            dockerfile: Dockerfile
            platform: arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: linux/${{ matrix.platform }}
          push: true
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.tag }}-${{ matrix.platform }}

  publish:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - 
        name: Create manifests
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          ghcr.io/${{ github.repository }}:${{ env.tag }} \
          --amend ghcr.io/${{ github.repository }}:${{ env.tag }}-amd64 \
          --amend ghcr.io/${{ github.repository }}:${{ env.tag }}-arm64
      -
        name: Push manifests
        run: |
          docker manifest push ghcr.io/${{ github.repository }}:${{ env.tag }}
